[project]
name = "mayan-task-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HusPhil009", email = "husphil200@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "greenlet>=3.1.1",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.3",
]

[project.scripts]
mayan-task-management = "mayan_task_management:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
