"""use int enum for status

Revision ID: 688fbfef4822
Revises: 4791cc0db270
Create Date: 2026-08-18 13:18:10.799217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "688fbfef4822"
down_revision: Union[str, Sequence[str], None] = "4791cc0db270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=postgresql.ENUM(
            "INCOMPLETE", "COMPLETE", name="task_status_enum"
        ),
        type_=sa.SmallInteger(),
        existing_nullable=False,
        postgresql_using="""
            CASE status
                WHEN 'INCOMPLETE' THEN 0
                WHEN 'COMPLETE' THEN 1
            END
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.SmallInteger(),
        type_=postgresql.ENUM("INCOMPLETE", "COMPLETE", name="task_status_enum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
